devtools::load_all("../gfplot/")
devtools::load_all(".")

dc                  <- file.path("report", "data-cache")
dat                 <- list()
dat$survey_sets     <- readRDS(file.path(dc, "pbs-survey-sets.rds"))
dat$survey_samples  <- readRDS(file.path(dc, "pbs-survey-samples.rds"))
dat$comm_samples    <- readRDS(file.path(dc, "pbs-comm-samples.rds"))
dat$catch           <- readRDS(file.path(dc, "pbs-catch.rds"))
dat$cpue_index      <- readRDS(file.path(dc, "pbs-cpue-index.rds"))
dat$cpue_spatial    <- readRDS(file.path(dc, "pbs-cpue-spatial.rds"))
dat$cpue_spatial_ll <- readRDS(file.path(dc, "pbs-cpue-spatial-ll.rds"))
dat$survey_index    <- readRDS(file.path(dc, "pbs-survey-index.rds"))
dat$age_precision   <- readRDS(file.path(dc, "pbs-age-precision.rds"))

gfsynopsis::make_pages(dat, "pacific ocean perch")
gfsynopsis::make_pages(dat, "pacific cod")
gfsynopsis::make_pages(dat, "redbanded rockfish")
gfsynopsis::make_pages(dat, "shortraker rockfish")
