# Estimating population indices with spatiotemporal models

<!-- TODO - we really just used the outputs from the 2023 report... so I'm not sure what we should do here -->

SA: should the grid stuff from the last section go here?

We fit spatiotemporal models to the Multi-Species Small Mesh survey data for all species that had a proportion of positive sets $\ge$ 5%.
For the six species that did not have catch weights before 2003, we calculated the proportion of positive sets for 2003 to present.
However, of these species, only Blackbelly Eelpout met the 5% coverage threshold to be modelled.

We used the model outputs from (ref: Anderson et al. 2023) followed the methods described in Appendix A of the 2023 Synoptic Report (ref TODO).
We present the best model for each species-survey combination, chosen as the model with the lowest marginal AIC.

In 2022, 64% of trawls (57 fishing events) did not have doorspread values and so for these fishing events we calculated the mean doorspread of 2022 and used this for the missing values.
Our spatiotemporal models had constant spatial random fields and a random walk spatiotemporal random field.
In cases where models did not converge, the spatial random field was turned off (i.e., set to zero) and only the spatiotmporal random field was included.

We omitted poorly fitted models: those which did not meet convergence criteria, those where the maximum estimated CIs were greater than 10 times the maximum estimated biomass, and those where the mean coefficient of variation was < 1. Details are available in TODO SYNOPSIS REF.

\clearpage
