---
title: |
  "Assessing the quality of groundfish population indices derived from the Multispecies Small Mesh Survey"
french_title: Titre ici (*Nom latin de l'espèce*)
year: 2024
report_number: nnn
author: |
  Jillian C. Dunic,
  Sean C. Anderson
author_list: "Dunic, J.C., and Anderson, S.C."
region: Pacific Region
french_region: Région du Pacifique
isbn: ""
address: |
  Pacific Biological Station\
  Fisheries and Oceans Canada, 3190 Hammond Bay Road\
  Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  Station biologique du Pacifique\
  Pêches et Océans Canada, 3190 Hammond Bay Road\
  Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
phone: "(555) 555-5555"
author_footnote: "Email: First.Author@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  Since 1973, DFO has conducted the Multispecies Small-Mesh Survey (MSSM), which is the longest continuous fisheries independent monitoring time-series for groundfish off the coast of West Coast Vancouver Island (WCVI). The survey was designed to collect data to assess stock status of Pink shrimp (*Pandalus jordanii*) populations; however, groundfish species have also been sampled in this survey. The MSSM has the potential to serve as an important historical baseline for groundfish species off WCVI, given that the current synoptic trawl surveys that are designed for Pacific groundfish began in or after 2003. However, changes to the MSSM, including shifts in the spatial area sampled, changes to gear used, and changes to groundfish sampling procedures, may affect the quality of MSSM groundfish popluation indices. Here, we examine changes to the MSSM and assess how these changes may affect interpretation of indices of relative biomass for groundfish. We then derive both design-based and spatiotemporal model-based groundfish population indices from the MSSM and compare these with other indices from the same region. Finally, we examine the distribution of lengths and ages sampled on the MSSM and compare these with the synoptic West Coast Vancouver Island trawl survey (SYN WCVI). We identify some instances where the MSSM may have detected signs of rockfish recruitment earlier than in the SYN WCVI survey. Spatiotemporal, model-based indices of abundance produced similar trends as the design-based indices for most species and may be better suited for calculating an index over the full time period given the changes in spatial sampling. However, changes to the survey such as the switch to comprehensive species sorting, sampling, and identification in 2003, coupled with a lack of calibration data, mean that there are large uncertainties with the pre-2003 data. 

french_abstract: |
  Depuis 1973, le MPO effectue l'enquête multispécifique à petites mailles (MSSM), qui est la plus longue série chronologique continue de surveillance indépendante des pêches pour les poissons de fond au large de la côte ouest de l'île de Vancouver (WCVI). L'étude a été conçue pour collecter des données afin d'évaluer l'état des stocks de crevettes roses (*Pandalus jordanii*) ; cependant, des espèces de poissons de fond ont également été échantillonnées dans le cadre de cette étude. La SSMM peut servir de référence historique importante pour les espèces de poissons de fond au large de la COIV, étant donné que les enquêtes synoptiques actuelles au chalut conçues pour les poissons de fond du Pacifique ont commencé en 2003 ou après. Cependant, les changements apportés au MSSM, y compris les changements dans la zone spatiale échantillonnée, les changements dans les engins utilisés et les changements dans les procédures d'échantillonnage des poissons de fond, peuvent affecter la qualité des indices de population de poissons de fond du MSSM. Nous examinons ici les changements apportés au MSSM et évaluons comment ces changements peuvent affecter l'interprétation des indices de biomasse relative des poissons de fond. Nous dérivons ensuite des indices de population de poissons de fond basés sur la conception et sur des modèles spatio-temporels à partir du MSSM et nous les comparons à d'autres indices de la même région. Enfin, nous examinons la distribution des longueurs et des âges échantillonnés dans le cadre du MSSM et les comparons avec l'étude synoptique au chalut de la côte ouest de l'île de Vancouver (SYN WCVI). Nous identifions certains cas où le MSSM pourrait avoir détecté des signes de recrutement de sébastes plus tôt que dans le relevé SYN WCVI. Les indices d'abondance spatio-temporels basés sur des modèles ont produit des tendances similaires à celles des indices basés sur la conception pour la plupart des espèces et pourraient être mieux adaptés au calcul d'un indice sur l'ensemble de la période, compte tenu des changements dans l'échantillonnage spatial. Cependant, les changements apportés à l'étude, tels que le passage à un tri, un échantillonnage et une identification complets des espèces en 2003, associés à un manque de données d'étalonnage, signifient que les données antérieures à 2003 sont entachées de grandes incertitudes. 
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: true
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: true
type:
  techreport
knit: (function(input, ...) {
       csasdown::render()
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: [bib/mssm.bib]
header-includes:
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  autodep = TRUE,
  cache = FALSE, # !!
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(gfsynopsis)
```

```{r globals, cache=FALSE}
french <- TRUE
```
