---
title: |
  "A data synopsis for British Columbia groundfish: 2022 data update"
french_title: Titre ici (*Nom latin de l'espèce*)
year: 2023
report_number: nnn
author: |
  Sean C. Anderson,
  Jillian C. Dunic,
  Elise A. Keppel, and
  Andrew M. Edwards
author_list: "Anderson, S.C., Dunic, J.C., Keppel, E.A., and Edwards, A.M."
region: Pacific Region
french_region: Région du Pacifique
isbn: ""
address: |
  Pacific Biological Station\
  Fisheries and Oceans Canada, 3190 Hammond Bay Road\
  Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  Station biologique du Pacifique\
  Pêches et Océans Canada, 3190 Hammond Bay Road\
  Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
phone: "(555) 555-5555"
author_footnote: "Email: First.Author@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  The combination of fishery-dependent data, such as catch and effort, and
  fishery-independent survey data, such as biomass indices and age
  compositions, forms the backbone of most fisheries stock assessments. For
  British Columbia groundfish, vast quantities of such data are
  collected. However, the DFO Pacific groundfish section lacks the capacity to conduct formal
  stock assessments for most stocks annually, and therefore, much of these data
  are not summarized to represent the nature of the data holdings.
  Here, we update a reproducible report that gives a snapshot of population and
  fishing trends, growth and maturity patterns, as well as data availability,
  for 117 groundfish species in British Columbia.
  This update includes data up to 2022.
  Furthermore, this update adds four species, adds several indexes of abundance that combine related surveys (a coastwide trawl survey index, a coastwide longline survey, and an inside Vancouver Island waters longline survey) using spatiotemporal models, adds length and age composition data for two additional surveys, and adds an index of biomass from the multispecies small mesh survey.
  We intend to continue updating this report on an annual basis.
french_abstract: |
  La combinaison de données dépendantes de la pêche, telles que les captures et l'effort de pêche, et de données d'enquête indépendantes de la pêche, telles que les indices de biomasse et la composition par âge, constitue l'épine dorsale de la plupart des évaluations des stocks halieutiques. Pour les poissons de fond de la Colombie-Britannique, de grandes quantités de données de ce type sont collectées. Cependant, la section des poissons de fond du Pacifique du MPO n'a pas la capacité d'effectuer des évaluations formelles de la plupart des stocks chaque année, et par conséquent, la plupart de ces données ne sont pas résumées pour représenter la nature des fonds de données.  Ici, nous mettons à jour un rapport reproductible qui donne un aperçu des tendances de la population et de la pêche, des modèles de croissance et de maturité, ainsi que de la disponibilité des données, pour 117 espèces de poissons de fond en Colombie-Britannique.  Cette mise à jour inclut les données jusqu'en 2022.  En outre, cette mise à jour ajoute quatre espèces, plusieurs indices d'abondance qui combinent des enquêtes connexes (un indice d'enquête au chalut sur l'ensemble de la côte, une enquête à la palangre sur l'ensemble de la côte et une enquête à la palangre dans les eaux de l'île de Vancouver) à l'aide de modèles spatiotemporels, ajoute des données sur la longueur et la composition par âge pour deux enquêtes supplémentaires et ajoute un indice de biomasse provenant de l'enquête multispécifique à petites mailles.  Nous avons l'intention de continuer à mettre à jour ce rapport sur une base annuelle.
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: false
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: false
type:
  techreport
knit: (function(input, ...) {
       csasdown::render()
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: [bib/spp-refs.bib,bib/survey-refs.bib,bib/synopsis.bib]
header-includes:
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  autodep = TRUE,
  cache = FALSE, # !!
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
```

```{r load-libraries, cache=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(gfsynopsis)
```

```{r globals, cache=FALSE}
french <- TRUE
```
