# International Pacific Halibut Commission survey updates {#app:iphc}

Data for the IPHC spatiotemporal model index are now derived directly from the [IPHC website](https://www.iphc.int/data/fiss-survey-raw-survey-data/).
The code to process these data is housed in the [gfdata package](https://github.com/pbs-assess/gfdata) within the `data-raw` folder.
The function `gfdata::load_iphc_dat()` joins data from the package data objects `gfdata::iphc_catch` and `gfdata::iphc_sets` into a single data frame for a given species or for all species at once.

Here we list the important steps to the process:

- We visit <https://www.iphc.int/data/fiss-survey-raw-survey-data/>, expand the year range to 1998--2023, select "2B" from "IPHC Regulatory Areas", leave all other options at defaults, and select "Excel format" from the "Crosstab" section. We scroll down to select "Non-Pacific Halibut Data" and download it. Once done, we similarly select "Set and Pacific halibut data" and download it. Our code then proceeds through the following steps.

- We replace Rougheye and Blackspotted Rockfish data rows with the summed counts of these two species since we report the complex of these species.

- We change "citharichthys spp" to "citharichthys sordidus". I.e., we assume Sanddabs are Pacific Sandabs as was done in the gfiphc package.

- We convert Rock Sole into Southern Rock Sole as was done in the gfiphc package. To do that we convert "lepidopsetta sp." into "lepidopsetta bilineata".

- We replace common names in the IPHC dataset with common names from the GFBio database based on a join on scientific names.

- We calculate effective skates in 2012 as hooks observed divided by average number of hooks per skate since these are missing in the raw data.

- We fill in cases of zero catch for a given species at a given station in a given year.

- We identify a set of stations from a 2018 expansion into inside Vancouver island waters and omit these from spatiotemporal models since this region is not sampled in any other years. These stations are: 2207, 2204, 2203, 2201, 2212, 2211, 2215, 2216, 2219,  2220, 2222, 2223, 2224, 2225, 2227, 2228, 2229, 2230, 2231, 2234, 2235, 2236, 2238, 2239, 2243, 2244, 2249, 2259, 2245, 2246.

- We import 1995--1997 data from the gfiphc R package, which draws on data from spreadsheets contained within that package [@anderson2019synopsis].

- We correct hooks observed for two sets that appear to be erroneous. (1) We recalculate hooks observed at station 2092 in year 2004 as average hooks per skate $\times$ number of skates hauled since the entered value (799) does not match 1.5 skates hauled and 100 hooks per skate. (2) In 2018 at station 2227, hooks counted is listed as 1390 but is corrected by multiplying 7 sets with an average 99 hooks per skate, resulting in 693 hooks observed.

We compared hooks observed and the number of fish observed per set between our new dataset and the dataset in gfiphc and see close agreement. 
Some minor differences arise because some sets deemed "usable" or "unusable" in GFBio now have the opposite coding in the data downloaded from the IPHC website. 
This affects a total of 48 sets (year-station combinations) over the full time series. 
At this point we do not have an explanation for these minor differences in usability columns---it appears these have been updated in the raw IPHC dataset that is now publicly shared.

We do not update the IPHC design-based index for 2023 (this requires a different data pipeline involving the gfiphc package), but we do plot the design-based index up to 2022 for comparison with the new version.
We note that the gfiphc package is still the appropriate dataset and tool for calculating a design-based IPHC survey index as described in @anderson2019synopsis.
The new dataset above is formed in a more streamlined process and is designed for use with geostatistical modelling.
