---
title: |
  "A data synopsis for Haida Gwaii Groundfish: 2025"
french_title: "Une synthèse des données pour les poissons de fond du Haida Gwaii: 2025"
year: 2026
report_number: 000
author: |
  Jillian C. Dunic and Daniel L. Curtis and Sean C. Anderson
author_list: "Dunic, J.C. and Curtis, D.L. and Anderson, S.C."
region: Pacific Region
french_region: Région du Pacifique
isbn: "ISBN GOES HERE"
address: |
  Pacific Biological Station\
  Fisheries and Oceans Canada, 3190 Hammond Bay Road\
  Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  Station biologique du Pacifique\
  Pêches et Océans Canada, 3190 Hammond Bay Road\
  Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
phone: "(555) 555-5555"
author_footnote: "Email: sean.anderson@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
  The combination of fishery-dependent data, such as catch and effort, and fishery-independent survey data, such as biomass indices and age compositions, forms the backbone of most fisheries stock assessments. For British Columbia groundfish, vast quantities of such data are collected. However, the Fisheries and Oceans Canada Pacific groundfish section lacks the capacity to conduct formal stock assessments for most stocks annually. To facilitate timely updates, we produce an annual reproducible report that gives a snapshot of population and fishing trends, growth and maturity patterns, as well as data availability, for 124 fish species, primarily focused on groundfish, but also other species of management interest. These reports present available data at broad spatial scales—coastwide, survey-region, or Pacific Marine Fisheries Commission Areas. As DFO enters into an increasing number of co-governance agreements with First Nations partners, it is important to have a common understanding of available data at both DFO’s management scale and at smaller scales that are relevant to the stewardship of resources in a Nation’s territory. This version of the report is a regional adaptation of the coastwide synopsis report, summarising data for Haida Territory up to 2025.
french_abstract: |
  La combinaison des données dépendant de la pêche, telles que les prises et l'effort de pêche, et des données de relevés indépendants de la pêche, comme les indices de biomasse et la composition par âge, constitue le pilier de la plupart des évaluations de stocks halieutiques. De grandes quantités de ces données sont recueillies pour les poissons de fond de la Colombie-Britannique. Cependant, la Section des poissons de fond du Pacifique de Pêches et Océans Canada n'a pas la capacité d'effectuer des évaluations formelles annuelles pour la majorité des stocks. Afin de faciliter des mises à jour en temps opportun, nous produisons un rapport annuel reproductible offrant un aperçu des tendances démographiques et de pêche, des profils de croissance et de maturité, ainsi que de la disponibilité des données, pour 124 espèces de poissons, principalement axé sur les poissons de fond, mais aussi sur d'autres espèces d'intérêt pour la gestion. Ces rapports présentent les données disponibles à de grandes échelles spatiales — l'ensemble de la côte, la région de relevé, ou les zones de la Commission des pêches maritimes du Pacifique. À mesure que le MPO conclut un nombre croissant d'ententes de cogouvernance avec des partenaires des Premières Nations, il est important d'avoir une compréhension commune des données disponibles à l'échelle de gestion du MPO ainsi qu'à des échelles plus fines pertinentes pour l'intendance des ressources sur le territoire d'une Nation. Cette version du rapport est une adaptation régionale du rapport de synthèse pour l'ensemble de la côte, résumant les données pour le territoire Haïda jusqu'en 2025.

citation_french: "FRENCH CITATION WILL GO HERE"
report_DOI: "DOI-HERE"
output:
 csasdowntex::techreport_pdf:
   french: false
   copy_sty: false
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: false
type:
  techreport
knit: (function(input, ...) {
       csasdowntex::render()
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: [bib/spp-refs.bib,bib/survey-refs.bib,bib/synopsis.bib]
header-includes:
  \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  autodep = TRUE,
  cache = FALSE, # !!
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos,
  optipng = "-strip all"
)
```

```{r load-libraries, cache=FALSE}
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
library(gfsynopsis)
```

```{r globals, cache=FALSE}
french <- TRUE
```
