\clearpage

# Index des espèces par nom commun {#sec:common-name-index}

```{r index-alpha-common, results='asis', cache=FALSE}
.spp <- gfsynopsis::get_spp_names()
spp_table <- .spp %>%
  mutate(species_common_name = gfsynopsis:::first_cap(species_common_name)) %>%
  mutate(section = paste0("\\pageref{sec:", spp_w_hyphens, "}")) %>%
  mutate(species_science_name = paste0("*", gfplot:::firstup(species_science_name), "*")) %>%
  mutate(species_science_name = gsub("Sebastes aleutianus\\/melanostictus complex",
    "S. aleutianus/melanostictus complex", species_science_name)) %>% 
  mutate(species_common_name = gsub("C-o Sole", "C-O Sole", species_common_name)) %>%
  mutate(species_common_name = gsub("Rougheye\\/blackspotted Rockfish Complex", 
    "Rougheye/Blackspotted Rockfish", species_common_name)) |> 
  mutate(species_common_name = gsub("North Pacific Spiny Dogfish", 
    "Pacific Spiny Dogfish", species_common_name)) |>
  mutate(species_common_name = gsub("Popeye", 
    "Popeye grenadier", species_common_name))

spp_table %>% arrange(species_common_name) %>%
  select(species_common_name, species_science_name, section) %>%
  csasdown::csas_table(align = c("l", "l", "l"),
   col.names = c("Nom commun", "Nom scientifique", "Page"))
```

\clearpage

# Index des espèces par nom scientifique {#sec:sci-name-index}

```{r index-alpha-sci, results='asis', cache=FALSE}
spp_table %>% arrange(species_science_name) %>%
  select(species_common_name, species_science_name, section) %>%
  csasdown::csas_table(align = c("l", "l", "l"),
   col.names = c("Nom commun", "Nom scientifique", "Page"))
```

\clearpage
