# Figures {#sec:synopsis-plots}

This section contains the main species-by-species data
visualizations.
Each species is shown on two pages with the same layout used
throughout.
See Section\ \@ref(sec:plot-descriptions) for detailed figure captions.
In addition to the figures, we also provide the
scientific name, taxonomic details, DFO species
code,
a link to the FishBase and WoRMS (World Register of Marine Species) web pages,
details of the most recent DFO Research Documents and Science Advisory
Reports, and any information related to designations by the Committee on the
Status of Endangered Wildlife in Canada (COSEWIC) and to listings under the
Species at Risk Act (SARA).
The species are ordered according to DFO species
codes. The Table of Contents at the beginning of the document includes links to
the species pages in order of species codes, and
Sections\ \@ref(sec:common-name-index) and\ \@ref(sec:scientific-name-index)
provide links to the pages sorted alphabetically by common and scientific name, respectively.
