# GROWTH AND MATURITY {#sec:growth-and-maturity}

## MATURITY OGIVES {#sec:maturity-models}

We fit maturity ogives as logistic regressions of maturity (mature vs.\ not
mature) against length or age:

\begin{align}
y_i &\sim \mathrm{Binomial}(\pi_i)\\
\mathrm{logit} \left( \pi_i \right) &= \beta_0 + \beta_1 x_i + \beta_2 F_i
\end{align}
where $y_i$ represents a 1 if fish $i$ is considered mature and a 0 if fish $i$
is considered immature. The $\beta$ parameters represent estimated coefficients,
$x_i$ represents either the length or age of fish $i$, and $F_i$ represents
a binary predictor that is 1 if the fish is female and 0 if the fish is male.
The variable $\pi_i$ represents the expected probability of fish $i$ being
mature. We only fit these models if there are at least 20 mature males, 20
immature males, 20 mature females, and 20 immature females to ensure reasonably
representative sampling and sufficient sample sizes.

## LENGTH-AGE MODELS {#sec:length-age-models}

We fit von Bertalanffy length-age growth models [@vonbertalanffy1938] with
Stan [@rstan2018] as:

\begin{equation}
  L_i \sim \operatorname{Log-normal}
  \left( \log(l_\mathrm{inf} (1 - \exp(-k (A_i - t_0)))), \sigma \right)
\end{equation}

where $L_i$ and $A_i$ represent the length and age of fish $i$,
$l_\mathrm{inf}$, $k$, and $t_0$ represent the von Bertalanffy growth
parameters, and $\sigma$ represents the log standard deviation or scale
parameter. We fit the models with the following priors:

\begin{align}
  k &\sim \mathrm{Normal}\left(0, 2\right)[0, \infty]\\
  l_\mathrm{inf} &\sim  \mathrm{Normal} \left(0, \varphi \right)[0, \infty]\\
  \sigma &\sim  \operatorname{Student-t}\left(3, 0, 2 \right)[0, \infty]\\
  t0 &\sim  \mathrm{Normal}(0, 20)
\end{align}

where $\varphi$ was set to twice the 99\% quantile of observed lengths for that
species. This ensures that the $l_\mathrm{inf}$ prior is on an appropriate scale
for a given species. These weakly informative priors were helpful when fitting
these nonlinear models to a large number of species making it is difficult to
adjust the optimization procedure on a species-by-species basis. For speed, the
model fits shown in this synopsis report are derived from the mode of the
marginal posterior distributions (MPD) as opposed to from full Markov chain
Monte Carlo (MCMC) sampling.

## LENGTH-WEIGHT MODELS {#sec:length-weight-models}

We fit the length-weight models as robust linear regressions of log(length) on
log(weight) using the `MASS::rlm()` function 'M'-estimator method
[@venables2002]. This approach downweights the influence of outlying values
and helps generate reasonable model fits across all species without handpicking
outlying measurements to discard. The model can be written as:

\begin{equation}
  W_i = a \cdot L_i^b \cdot e_i,
\end{equation}
with $W_i$ and $L_i$ representing the weight and length for fish $i$ and $e_i$
representing error that is given some distribution such as lognormal or Gamma.
The variables $a$ and $b$ represent the estimated length-weight parameters.
Following the common convention, we fit the model as:
\begin{equation}
  \log (W_i) \sim \mathrm{Normal} (\log (a + b L_i), \sigma),
\end{equation}
with a robust algorithm being substituted for the usual normal distribution as
written here.

