---
title: |
   Response to editor's and reviewers' comments
output:
  bookdown::pdf_document2:
    number_sections: no
    toc: no
    template: "response-sty.tex"
    keep_tex: true
fontfamily: libertine
fontsize: 12pt
header-includes:
    - \usepackage{array}
    - \usepackage{setspace}
geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
bibliography: "refs.bib"
csl: "fisheries.csl"
link-citations: yes
linkcolor: "black"
urlcolor: "black"
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(here)
opts_chunk$set(echo = FALSE, message = FALSE, warnings = FALSE)
```

**Andy adding some thoughts in bold. Not wedded to any of them. I'll leave TODO
in front of anything that definitely needs further edits/thoughts/discussion,
and just do some of the simpler ones.**

**To make a diff file (like Tracked Changes) Andy committed
paper-subm-fisheries.tex and then runs**

shell("latexdiff paper-subm-fisheries.tex paper.tex > diff.tex")

shell("pdflatex diff.tex")

**which creates a pdf with changes shown. Have to tweak the bib file if we add
anything. Sean - if you use something similar then great, else I can do this for
the final version.**


# Science Editor's Comments to Author {-}

I agree with both reviewers that your manuscript will be a useful and
interesting article for readers of Fisheries. However, unlike the first
reviewer, I do think some revisions are needed, but, unlike the second reviewer,
I would consider these to be minor rather than major. I have included my
editorial comments along with those of both reviewers.  Please look all of them
over and indicate whether or not you incorporated them into your revised
manuscript. For instances in which you chose not to incorporate a suggestion,
please provide a brief explanation of your reasons.

**We thank the editor for their positive comments. Please see below for our
responses to the reviewers' comments.**

When you revise your manuscript please highlight the changes you make in the
manuscript by using the track changes mode in MS Word or by using bold or
coloured text.

**Please see the file diff.pdf, which shows the differences. TODO.**

# Reviewers' Comments to Author:

## Reviewer: 1

Comments to the Author

James Ianelli

This short paper highlights a much needed practice in global
fisheries---improvements in transparency on data availability and presentation
aspects. I like that it focuses attention on a data report without sacrificing
valuable pages in a journal like yours.

**We thank the reviewer for his encouraging review.**

There were some minor points that could be addressed.

1) They emphasize throughout the document the multispecies nature of the
work. This is certainly true in the broad sense of including many species
plotted out in the same way, but each ''view'' (visualization) is single
species. To avoid confusion with what a multispecies presentation might look
like (with more than one species in a visualization), this wording might be
modified.

**TODO We only say 'multi-species' twice, including the title. Andy tried adding in
``Given the large amount of data it was necessary to visualize data independently
for each of the multiple species. Our general approach could certainly be used
to view related species in single visualizations.'' (in this commit, end of
paragraph 9). But it sounds overly defensive.
Maybe best just to change the title to**

**``Reproducible visualization of raw fisheries data for 113 species improves
transparency, assessment efficiency, and monitoring''**

**I think we weren't keen on that version at some point, but may be the simplest
way to address Jim's point, which is fairly valid. And avoids getting tangled up
with explaining why multi-species isn't quite multi-speces.**

2) The introduction extolls the virtues of visualizations for communication and
summarizations. I'm a big fan. However, there are some cases where flashy
visualizations are misleading and exaggerate trends and spatial patterns. While
I think the authors do a fantastic job of highlighting sample sizes etc., more
mention of the issue and how they address it could be made.

**TODO Not quite sure what to say, or where.**

3) I would like to have seen more text on how to shoehorn this type of graphical
presentation into a different setting outside of PBS/DFO’s system.

**TODO I think asking for a bit about our workflow, R packages etc.? I see we
have something commented out about it not being just about the R packages, but
maybe we need to say something about this. Think this helps with one of Reviewer 2's
comments also.**

4) The main document (Anderson et al. 2019) is great. I was interested to see
that there was an accessibility (for vision impaired etc.) link at the bottom of
the website. Before seeing that I was curious if something mentioning how a
vision impaired person might find such graphics useful?
Within the US, ''alt-text'' is meant to be used which describes what’s in a
particular figure. This sounds like a big task for this type of
presentation. But perhaps this could be brought out in the discussion
somewhat. Specifically, another movement is to have visualizations also having
direct links to the underlying data ... which might be another advancement in
future.

**Unfortunately, the graphical nature of the visualisations does not easily
allow an 'alt-text' description, especially for an automatically generated
report containing thousands of individual figures. In DFO we have automated the
generation of rather rudimentary 'alt-text', but it seems a bit peripheral to
mention here.**

## Reviewer: 2

GENERAL COMMENTS

The proposed article is relevant, in a theme that must be addressed not only
from the scientific perspective, but also involving the users of the
resources. Results and maps presented thought-provoking, but its interpretation
is not simple, requires a degree of experience, and as separate illustrations
should be designed so that they can be interpreted just to see them, which does
not happen in the case.

**We thank the reviewer for their comments. We have added the following text to
emphasise that the included figures are just meant to be examples, not
explicitly used for understanding data concerning a particular species:**

**page ?? line ??: ``Figures 1--3 are included here as examples to demonstrate our
visualizations; see Anderson et al. (2019) for full descriptions and
interpretations of the data.''**

**TODO: fill in all `page ?? line ??' when finalised revised version.**

As a result of the review I consider that the document should be improved to
achieve a clear structure in contents (in my opinion there are texts not located
in the corresponding section), strengthen the methodology (currently contains
information that should be passed to the introduction and a series of the
authors' considerations when developing the work, without considering how it was
done) and improve discussion is essential. The above to achieve internal
consistency and meet the objectives set by the authors themselves.

**TODO: Could move first paragraph of Methods into end of Introduction, since,
yes, it does describe goals (not actual Methods). I think this may be enough
(could also refer to any tweak in the discussion wrt number 2 below). Aha --
moving the first two paragraphs is explicitly what the reviewer suggests in 3 (I
disagree with moving second paragraph though).**

SPECIFIC COMMENTS

1. The adstract mentions that visualizations should serve as a critical
   component of the scientific process and facilitate the understanding and
   commitment of the participants. However, these points are not taken into
   account because the illustrations require strengthening to be easily
   understood, there is no talk of the opinion of the users in the design of the
   exits, there was no paragraph found that illustrates with the visualizations
   can give rise to raise scientific questions.

**Regarding the illustrations needing strengthening to be understood, see our
above new sentence ``Figures 1--3 are included here...''. Regarding the opinion
of the users, we feel that we already covered this explicitly in the lines (page
?? line ??):**

**``Throughout report development we solicited feedback from stakeholders and
other potential users of the report on which data to include as well as on
report structure and design. We also sought feedback from data experts for
various species groups to ensure that the data being captured were accurate,
complete, and presented faithfully.''**

**Similarly, we explicitly noted (page ?? line ??) that ``Such an approach
facilitates new research ideas and addresses questions such as:'' and then
listed five explicit questions.**

2. Examples of visualizations are mentioned in the introduction, however this
background is not used to discuss, compare and conclude about the work done. It
seems to me that this should be considered to strengthen the discussion, and
perhaps to defend the strengths of the proposal in this document.

**For this short manuscript we feel that to return to all the examples in the
introduction is not appropriate. However, we note that we have already
contrasted our work with the ICES (2019) summaries of stock-assessment
output. And our report is novel in that it presents raw data, as we mentioned
in the introduction.**

3. The first two paragraphs of the methodology can be used to close the
introduction (lines 85-96). In the following paragraphs of this section we do
not find how it was done, rather all the design approaches and
considerations. In that sense, for non-experts on the subject it would be very
useful to strengthen this chapter, perhaps this is simple if a diagram or figure
that synthesizes is used.

**As suggested, we have moved the first paragraph of the Methods to the end of
the Introduction (TODO). However, the second paragraph does include our explicit
approach of developing a family of R packages, that we believe should remain in
the Methods section. TODO: expand on the design considerations? Not sure if a
figure would really help [I can't see that there's a limit on number of figures,
but good to keep it short].**

4.The discussion seems internal. It aims to explain results, considerations and
propose new ideas to improve this work. However there is no discussion with
other similar systems. For example, what is proposed in Australia is very
educational, easy to understand for all public, very visual; but on the other
hand it does not have the scope of what is proposed. What I can see of ICES does
not have the quality and complexity of what you present in this
document. Perhaps some paragraphs in this area would result in a relevant
academic discussion.

**TODO: maybe. Might get repetitive though.**

# Science Editor's Detailed Comments

**Text: suggested changes are shown in bold , and omissions are shown with strikethroughs.**

Lines 9-11  Our implementation consists of two pages per species that includes show standardized visualizations of temporal trends and spatial distributions of commercial catches and survey indices, plus along with analyses of ages, lengthssize, maturity, and growth, all on two pages per species.

Line 13   transparency about data holdings, and makes the data available for

Line 14  parties. We encourage others agencies to consider similar approaches for their own data.

Line 23  and as well as understanding species trends

Line  57  Shackell 2013), and. nNo agency, to our

Line 79  the majority of most monitoring data

Line 81  cannot be shared in raw format due to privacy laws. Furthermore, the data

Line  90  are useful elsewhere, (e.g., in stock assessments).

Line  93  extracted from databases and treated prior to plotting, and developed the

Lines 100 & 101  packages in a modular format so that that individual functions could be used for other purposes—for examplee.g., so the data could be extracted

Line 103  In designing the report, we made the following

Line 108  colour meaning throughout (e.g., data from a given survey

Line 113  interest, and as well as those that are regularly caught

Line 129  species groups to ensure that the data being captured were accurate,

Line 134  34 rockfish species; 16 elasmobranch species and one chimaera species;

Text –continued

Line 136  eelpout species, three prickleback species, and seven other perciform species; and

Line 142  stakeholder engagement, and monitoring (Table 11), and has been well-received by stakeholders,

Line 146  a report that presentsing up-to-date population trends

Line 147  and research surveys. Additionally, the visualizations

Line 149  of the species included in our report, and are not

Comment re Lines 153 & 154  Could this be reworded so that it reads more clearly: “The approach … provides a mechanism for regular review of data for indication of surprises by relevant parties”  Could you omit “for indication of surprises by relevant parties,” or use this as another item that is facilitated by your method?

Line 158  and useful. We first discuss the public availability and format aspects. Undoubtedly, many agencies

Lines 161-163  outside of an agency. Even within an agency, having a single go-to report (as a pdf file) will increase speed and efficiency since these tools still require time and expertise to use, and effort can be is duplicated if when several people independently extract data on the same species—having a single go-to report (as a .pdf file) is fast and efficient.

Lines 168-171  As examples, in our case, up to ten survey indices can be compared amongst themselves and with commercial CPUE,; length and age composition patterns are plotted for all surveys together,; and spatial and temporal survey patterns can be considered simultaneously.

Lines 172 & 173  Internally, the approach we describe here provides many features and resulting benefits that we imagine would extend to any agency

Line 177  overview of available data types and quantities and, therefore, what management procedures
Text-continued

Lines 180 & 181  longline surveys and discovered that the survey design was not followed precisely that year. but tThis information had been lost to current stock assessment scientists.

Lines 183-184  For instance, immediately after the 2019 survey data were entered, we regenerated the report and skimmed survey indices for any major changes.  We noteding a rapid decline in some Arrowtooth Flounder survey indices and early signs of recovery of Bocaccio rockfish in survey indices and age compositions.  These have played into discussions of assessment prioritization and work planning.

Line 188  generation because the product is most useful with up-to-date data and it

Lines 203 & 204  sources which that are most applicable for specific species rather than those presented in the report which that were widely applicable to many species, analyze data on a finer spatial basis

Lines 205 & 206  stocks along the BC coast rather than coastwide analysis), or make considerations for special cases that are not considered included in our report.

Line 213  face monitoring multiple ecosystem elements

Table 1 – Under “Example Benefits” – Use similar phrasing for examples:

4th example
Instead of using “All fisheries dependent and independent index trends can be compared for similarities and contrasts”, use “Allows comparisons of all fisheries dependent and independent index trends for similarities and contrasts”

5th example
Instead of using “Spatial and temporal trends can be considered simultaneously”, use “Allows simultaneous consideration of spatial and temporal trends”
7th example
Instead of using “Noticing recent declines in multiple survey indices for a stock with no planned assessment”, use “Shows recent declines in multiple survey indices for stocks with no planned assessment”

8th example
Instead of using “Can assist discussions of stock assessment prioritization”, use “Assists in discussions of stock assessment prioritization”

9th example
Instead of using “Industry associations that have contributed time or money to survey programs can see their data being used”, use “Allows industry association that have contributed time or money to survey programs to see how their data is being used”

10th example
Instead of using “Data collected with tax-payer funds are not left hidden on internal government servers”, use “Ensures data collected with tax-payer funds are not left hidden on internal government servers”

11th example
Instead of using “Unlike internal tools, makes visualized data available to public, Indigenous people, NGOs, fishing industry, fishery managers, consultants”, use “Makes visualized data available to public, Indigenous people, NGOs, fishing industry, fishery managers, consultants”

12th example
Instead of using “Open data is not enough—many interested parties lack the skills, time, and institutional knowledge to turn raw data into interpretable graphics”, use “Turns raw data into interpretable graphics for interested parties lacking the skills, time, and institutional knowledge to do this with avialable data (i.e., open data is not enough)”

16th example
Instead of using “Detecting consistent deviations in survey indices across stocks indicating historical deviations from survey design“, use “Shows consistent deviations in survey indices across stocks that indicate historical deviations from survey design”

17th example
Instead of using “Detecting fish lengths entered in wrong units”, use “Allows detection of fish lengths entered in wrong units”



Figure Captions – Do not use parenthesis for scientific fish name following common name (also italicize genus and species of scientific names):

Figures 1 & 2 - do not use “Silvergray Rockfish (Sebastes brevispinis)”.  Instead, use “Silvergray Rockfish Sebastes brevispinis”

Figure 4 – do not use “Canary Rockfish (Sebastes pinniger), Petrale Sole (Eopsetta jordani), and Sand Sole (Psettichthys melanostictus)”.  Instead use “Canary Rockfish Sebastes pinniger, Petrale Sole Eopsetta jordani, and Sand Sole Psettichthys melanostictus.”
